-- Bougsk backend schema — initial launch tables.
-- NOTE: `coupons` and `reviews` tables are deliberately deferred to a later
-- migration. They are add-later features, not launch-blocking, per the spec.

-- categories
create table categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text,
  sort_order int default 0,
  created_at timestamptz default now()
);

-- products
create table products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references categories(id),
  name text not null,
  slug text unique not null,
  description text,
  scent_notes text[], -- e.g. {"Amber","Sandalwood","Smoke"}
  ingredients text,
  burn_time_hours numeric,
  weight_grams numeric,
  price_inr numeric not null,
  compare_at_price_inr numeric, -- optional strike-through "was" price
  stock_quantity int not null default 0,
  is_active boolean not null default false, -- the admin panel's "go live" toggle
  is_featured boolean not null default false,
  image_paths text[] not null default '{}', -- paths in Supabase Storage, ordered
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- product_variants (optional — sizes like "Small / 120g", "Large / 250g")
create table product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references products(id) on delete cascade,
  name text not null,
  price_inr numeric not null,
  stock_quantity int not null default 0,
  sku text unique
);

-- orders
create table orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null, -- e.g. "BOUGSK-000123", generated by the Edge Function
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  shipping_address jsonb not null, -- {line1, line2, city, state, pincode}
  subtotal_inr numeric not null,
  shipping_fee_inr numeric not null default 0,
  total_inr numeric not null,
  payment_status text not null default 'pending'
    check (payment_status in ('pending','paid','failed','refunded')),
  payment_gateway_order_id text, -- Razorpay order id
  payment_gateway_payment_id text, -- Razorpay payment id, once paid
  order_status text not null default 'placed'
    check (order_status in ('placed','confirmed','packed','shipped','delivered','cancelled')),
  courier_name text,
  tracking_number text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- order_items — a snapshot of what was bought, so later price/name edits never change past orders
create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references orders(id) on delete cascade,
  product_id uuid references products(id),
  product_name text not null,
  variant_name text,
  unit_price_inr numeric not null,
  quantity int not null,
  line_total_inr numeric not null
);

-- site_settings — admin-editable, single-row-per-key config (WhatsApp number, shipping fee, banner text)
create table site_settings (
  key text primary key,
  value jsonb not null
);

-- admins — allow-list of who may sign in to the admin panel (usually exactly one row)
create table admins (
  id uuid primary key references auth.users(id),
  email text unique not null
);
